### PR TITLE
Updated the copy for field guide doc

### PR DESCRIPTION
**Pull request by jdamis4XD**
Updated the copy as it pertains to TLC ticket #315,  Deciding What to Buy section

## Changes proposed in this pull request:

-
-
-

## security considerations

[Note the any security considerations here, or make note of why there are none]

### CODE REVIEW

**Review by juliaklindpaintner — APPROVED** [review]
Looks good to me!

**Review by jskinne3 — APPROVED** [review]
This is a quibble that might not be important, but, when I view [the PDF in the preview deployment](https://federalist-8bc0b42c-5fd0-4ae8-9366-cd9c265a4446.sites.pages.cloud.gov/preview/18f/guides/jdamis4XD-patch-2/assets/derisking/dist/federal-field-guide.pdf) in my browser the text "research and solicitation" looks slightly shifted vs the surrounding text.

Screenshot 2024-02-21 at 4 23 41 PM

**Comment by jdamis4XD** [comment]
That is odd. Attached is what the preview looks like from the uploaded
file  (from Google drive
<https://drive.google.com/file/d/1HWEqiHSQUJlVL7wxVyaYbQtjYnqPDj8I/view?usp=drive_link>
):

**Comment by juliaklindpaintner** [comment]
@jskinne3 @jdamis4XD I'm not seeing that when I open the PDF from the preview build 🤷‍♀️ 

Screenshot 2024-02-22 at 9 36 19 AM

**Pull request merged**
