### PR TITLE
Implement 404 page designs

### PR DESCRIPTION
**Pull request by igorkorenfeld**
## Changes proposed in this pull request:
This PR updated the 404 page design to match the [new designs](https://www.figma.com/file/6WuJ9nxQvmkzxlUPoqTmJP/18F-Guides-and-Methods?type=design&node-id=7-3497&mode=design&t=Ca48fWm1dw9wVwOZ-0). 

In addition the PR moves the data for the default navigation so that is grouped with all other navigation lists, rather than being in the `site.yaml` file

👓 [Preview](https://federalist-8bc0b42c-5fd0-4ae8-9366-cd9c265a4446.sites.pages.cloud.gov/preview/18f/guides/ik/implement-404/404.html)

### CODE REVIEW

**Review by eric-gade — COMMENTED** [review]
Just making sure we have the nav we want. The design has "Home" and "More 18F guides" but the demo only has "18F guides home". I can imagine why it does (there's no difference between the two), but just want to make sure it's intentional.
  
Screen Shot 2023-11-01 at 11 33 31 AM
Screen Shot 2023-11-01 at 11 33 25 AM

Otherwise, lgtm 👍

**Comment by igorkorenfeld** [comment]
Good observation. The issue I was working around was that "Home" and "More 18F guides" would lead to the same place (at least in production). With that in mind, it made sense to me that we only need one of them. I didn't choose "Home" because I thought that if a user mistypes it/is linked to a 404 page from a particular guide, they may expect "Home" to take them to that guide's home page. Meanwhile, the word "More" in "More 18F guides"  doesn't make as much sense to me when we are not showing any other navigation or the guide the user is on. 

Wanted to check in with @melchoyce, does this make sense to you? I know you are going to be working on a related issue.

**Comment by melchoyce** [comment]
Related to #507

(Will take a closer look this afternoon)

**Comment by melchoyce** [comment]
I'd give the bottom a little more padding—maybe 6rem instead of 4rem:

image

I think since we can't know what guide someone is either going to or coming from it makes sense to just have the one link—let's figure out the best copy for that and apply it to both this template and #507.

**Comment by igorkorenfeld** [comment]
@melchoyce I updated the implementation with the suggestions. There isn't a token for 6rem/96px, the closet one is for 5rem/80px – which looks ok to me. What's 16px between friends you know? But happy to make an adjustment if it feels too tight.

I've implemented the secondary nav too. I went with a bold weight, but no problem to change it to the regular weight if it feels  like it's competing. 

[Preview](https://federalist-8bc0b42c-5fd0-4ae8-9366-cd9c265a4446.sites.pages.cloud.gov/preview/18f/guides/ik/implement-404/404.html)

Since we've taken out the search bar for now, here is a screenshot of what it looks like when the search bar is there. 

screenshot of updated 404 page preview

**Comment by melchoyce** [comment]
> There isn't a token for 6rem/96px, the closet one is for 5rem/80px – which looks ok to me. What's 16px between friends you know? But happy to make an adjustment if it feels too tight.

Good call—I think it works!

Looking great overall. One minor point: when there isn't a search bar, is there an easy way to vertically center the secondary nav? If not, it's fine as-is, but I think centering would make it feel more balanced. (It looks great when there is a search bar!)

**Comment by igorkorenfeld** [comment]
@melchoyce Because of the way the nav is styled in the template, it's unfortunately not so simple. I would definitely fix it if we didn't plan to add search back in soon. But since that is the plan, I am not sure it's worth the effort. 

@eric-gade small re-review ask – would you mind taking a look at the secondary-nav implementation?

**Comment by melchoyce** [comment]
> @melchoyce Because of the way the nav is styled in the template, it's unfortunately not so simple. I would definitely fix it if we didn't plan to add search back in soon. But since that is the plan, I am not sure it's worth the effort.

K, let's ignore then 👍

**Review by eric-gade — APPROVED** [review]
Works on my end 👍

**Pull request merged**
