### PR TITLE
Add introduction page for v2 De-risking Guide

### PR DESCRIPTION
**Pull request by nateborr**
## Changes proposed in this pull request:

Add the structure and a first page for the v2 De-risking Government Tech guide to the `derisking-government-tech` feature branch.

- Create file structure and navigation for new v2 De-risking Guide
- Add introduction page content and styling
- Stub out additional pages for 1st and 2nd level navigation

### Notes on implementation

- I've duplicated the `chapter_image.html` include from the v1 De-risking Guide, since the plan is to remove the original guide once v2 has been up for several months.
- The 2x2 "What's in this guide" section is implemented with the [USWDS card component](https://designsystem.digital.gov/components/card/). I added SCSS styles for layout settings that I couldn't solve with USWDS utility classes.

## testing

Beyond the automated validations on the PR, manually test the following on a PR build:

- Visit the `/derisking-government-tech/` route on the PR build URL and confirm it loads the Introduction page: https://federalist-8bc0b42c-5fd0-4ae8-9366-cd9c265a4446.sites.pages.cloud.gov/preview/18f/guides/drg-v2-add-introduction-page/derisking-government-tech/
- Confirm that the content, layout, and images on the intro page look correct
- Shake out the page's responsiveness when the browser window is resized
- Check mobile device rendering using browser dev tools
- Confirm meta title, meta description, and social meta tags are present in the Introduction page source
- Shake out the top and left nav (additional pages should exist but contain only titles and "TK")

## security considerations

No security considerations: These updates use the existing framework and patterns of the 18F Guides site.

### CODE REVIEW

**Comment by melchoyce** [comment]
Noticed on the Introduction page the icons get super tiny once the layout switches to one column:

image

Can we have the image sizing stay proportional to the container size?

Under "what's in this guide," the linked title of each section should be bold. So:
- Understanding and choosing a software solution
- Four key principles for effective custom software development
- Buying custom software development services
- Working with a vendor development team

Also, is there any way to move the citation up to the end of the introduction section? 

For layout stuff—should I hold off on feedback until the end? For example, changing the font size and adjusting the padding on the cards:

image

And ensuring there's equal vertical spacing between `hr`s and the elements above/below them (32px/2rem):

image

**Comment by nateborr** [comment]
Thanks @melchoyce ! 

> For layout stuff—should I hold off on feedback until the end?

I'll aim to address your comments above, although if any of them is a bigger effort I may defer it for a later PR. I expect most of the style tune-ups will apply to the rest of the pages once I add them so I'll try to dial them in now. Please let me know any other style issues you're seeing (I'm also happy to review it with you in a quick meeting if that's easier for a lot of small things).

> is there any way to move the citation up to the end of the introduction section?

I used a standard [markdown footnote](https://www.markdownguide.org/extended-syntax/#footnotes) like we do in the other guides, and the markdown renderer puts the footnotes at the end of the document. I expect we can do it with raw HTML, but can you confirm that this should look different than the other existing guides in this case?

**Comment by melchoyce** [comment]
> Please let me know any other style issues you're seeing

Just the cards:

| Mockup | Site |
|--------|--------|
| image | image | 

And the `hr` spacing: 

| Mockup | Site |
|--------|--------|
| image | image | 

**[Figma dev link](https://www.figma.com/design/w5nNfRFN582jEYOKRVUmSs/Derisking-Guide?node-id=43-910&focus-id=246-3187&m=dev)**

---

> I used a standard [markdown footnote](https://www.markdownguide.org/extended-syntax/#footnotes) like we do in the other guides, and the markdown renderer puts the footnotes at the end of the document. I expect we can do it with raw HTML, but can you confirm that this should look different than the other existing guides in this case?

Okay, let's stick with it as-is so we don't need to make anything custom. No change needed.

**Review by melchoyce — APPROVED** [review]
LGTM!

**Review by edwintorres — APPROVED** [review]
I tested it locally, reviewed the code, LGTM.

I had some issues with the installation and running it, but nothing related to the code submitted here which should be merge. Just highlighting the issue here as it's my first code review.

**Pull request merged**
