### PR TITLE
Add code to highlight current heading in the sidenav

### LINKED ISSUE #282: 🟡 As a visitor, I can recognize where I am in relation to the whole page
**Background**
The [USDS Discovery Sprint Guide](https://sprint.usds.gov/), which also uses the Federalist template with sidenav, highlights the active sidenav section as you scroll. This would help our readers, particularly on our very long pages. 
Should we do something a bit more visible than the default darker gray/bold treatment for the active link?
Screen Shot 2021-01-04 at 4 44 27 PM

**Acceptance criteria** 
- [ ] As you scroll the Research > Plan or Do page (examples of long pages), the side navigation highlights as you scroll
- [ ] On small screens, the new highlighting functionality may still work, but does not impact the links present at page top

**Tasks**
- [ ] Design treatment
- [ ] Implement

**Definition of done**
- [ ]  One of the POs has approved the change

### PR DESCRIPTION
**Pull request by caleywoods**
Fixes #282 

## Changes proposed in this pull request:

- Adds some JavaScript that uses the scroll event to highlight the currently active section (`<h3>`). 
- This code was borrowed from the [USDS sprint website](https://github.com/usds/discovery-sprint-guide/blob/main/assets/js/app.js#L10)

## security considerations

None

### CODE REVIEW

**Comment by caleywoods** [comment]
@bpdesigns @a-chappelear @cantsin Here's the [Project Setup link ](https://federalist-8bc0b42c-5fd0-4ae8-9366-cd9c265a4446.sites.pages.cloud.gov/preview/18f/guides/caley/highlight-active-sidenav/engineering/tools/project-setup/)on the build preview with the new changes. I think this is what we were after.

**Comment by caleywoods** [comment]
@igorkorenfeld Mentioned the [code running in the derisking portion](https://github.com/18F/guides/blob/main/assets/derisking/js/current-link.js) of the guide that is currently doing this. I'll take a longer look at it later this week but on the surface I think the JS in this repo should be updated to copy (and then replace) the derisking guide code.

**Comment by caleywoods** [comment]
@igorkorenfeld I've updated the code to what was present in the derisking JavaScript and updated it to work with `<h2>` elements. [Here's a preview](https://federalist-8bc0b42c-5fd0-4ae8-9366-cd9c265a4446.sites.pages.cloud.gov/preview/18f/guides/caley/highlight-active-sidenav/derisking/state-field-guide/basic-principles/) of one of the de-risking sections.

**Review by cantsin — APPROVED** [review]
LGTM. ~One question though, I thought this was built in USWDS out of the box? I may be mistaken, though.~ I see the comment in the referenced ticket, feel free to merge!

**Pull request merged**
