### PR TITLE
Rework de-risking guide 2.0 navigation and title

### PR DESCRIPTION
**Pull request by nateborr**
## Changes proposed in this pull request:

[PR build](https://federalist-8bc0b42c-5fd0-4ae8-9366-cd9c265a4446.sites.pages.cloud.gov/preview/18f/guides/drg-v2-rework-nav/derisking-government-tech/)

### Update the De-risking Guide 2.0's nav:

- In the primary nav:
  - Change "Home" to "Read the guide" and add drop-down submenu items for guide pages
  - Edit navigation titles
- Implement guide-specific secondary nav links and add "Previous version" for the de-risking guide 2.0

(Secondary links are in the top right of the site header; in production the only one is "More 18F guides". See: https://designsystem.digital.gov/components/header/extended/)

### Remove "2.0" from the guide title

- Update nav links and page copy to remove "2.0"
- Update the guide icon on the About page

## Testing

Beyond the automated validations on the PR, manually test the following on a PR build.

### New secondary nav behavior

- Confirm that the de-risking v2 guide contains a "Previous version" link in the upper right portion of the site header, which links to the v1 de-risking guide
- Shake out a few other guides (accessible from the home page within this PR build) and confirm that the only secondary link is "Other 18F guides", as before
- Review the developer.md documentation update

### Document title updates

- Confirm that the guide title is now "18F De-risking Guide"
- Confirm that the link text in the [v1 redirect banner](https://federalist-8bc0b42c-5fd0-4ae8-9366-cd9c265a4446.sites.pages.cloud.gov/preview/18f/guides/drg-v2-rework-nav/derisking/) is now: "This is the original guide. Check out the new version!"
- Check that "2.0" no longer appears on the [About](https://federalist-8bc0b42c-5fd0-4ae8-9366-cd9c265a4446.sites.pages.cloud.gov/preview/18f/guides/drg-v2-rework-nav/derisking-government-tech/about/) page
- Confirm that the icon on the About page no longer contains the text "2.0".

## security considerations

No security considerations: These updates use the existing framework and patterns of the 18F Guides site.

### CODE REVIEW

**Comment by nateborr** [comment]
@melchoyce if you do another PDF update on 8/30 let me know and I'll make the change in this PR.

**Comment by ameliaswong** [comment]
Sorry I didn't catch this earlier @nateborr but could we change the banner text to "This is the original guide. [Check out the new version!](https://federalist-8bc0b42c-5fd0-4ae8-9366-cd9c265a4446.sites.pages.cloud.gov/preview/18f/guides/drg-v2-rework-nav/derisking-government-tech/)

**Comment by nateborr** [comment]
> Sorry I didn't catch this earlier @nateborr but could we change the banner text to "This is the original guide. [Check out the new version!](https://federalist-8bc0b42c-5fd0-4ae8-9366-cd9c265a4446.sites.pages.cloud.gov/preview/18f/guides/drg-v2-rework-nav/derisking-government-tech/) (I'd like to avoid using "version" twice.)

This change is in place.

**Review by peterrowland — APPROVED** [review]
√

**Pull request merged**
