### PR TITLE
Update Brand guide todo

### PR DESCRIPTION
**Pull request by melchoyce**
Replace "TODO" with a link to this github repo

### CODE REVIEW

**Review by jskinne3 — APPROVED** [review]
You could have kept the `/new` but I guess it's fine either way

**Review by echappen — APPROVED** [review]
TY!

**Comment by melchoyce** [comment]
I asked about `/new` in #171, but I can update again if we think we'll want that for all of the links? This repo has multiple issue templates, but the old repos didn't.

**Comment by echappen** [comment]
No need to update here. I think it's good to link to the full list of issues (i.e. using a link without `/new`), so that people wishing to create an issue can be prompted to see if a similar issue already exists.

**Pull request merged**
