### PR TITLE
Move tertiary engineering sections 

### PR DESCRIPTION
**Pull request by igorkorenfeld**
## Changes proposed in this pull request:
This PR reformats the "Data Act" and "Micropurchase" pages to be subsections of the "Architecture reviews" page (under our Approach), following the decision made in [TLC/338](https://github.com/18F/TLC-crew/issues/338). It updates the sidenav accordingly. 

This closes [TLC/338](https://github.com/18F/TLC-crew/issues/338)

👓 [Preview](https://federalist-8bc0b42c-5fd0-4ae8-9366-cd9c265a4446.sites.pages.cloud.gov/preview/18f/guides/ik/eng-sidenav/engineering/our-approach/architecture-reviews/)

### CODE REVIEW

**Comment by echappen** [comment]
[possible blocking observation] I'm not sure what intended behavior is here, but in mobile views, tables on this page expand beyond the content container without a scrollbar. If that's intended, then otherwise LGTM 👍 

Screenshot 2023-10-26 at 10 35 43 AM

Screen 2:

Screenshot 2023-10-26 at 10 35 29 AM

**Comment by igorkorenfeld** [comment]
Great catch @echappen, it looks like that happens on the existing guides as well. The first one does seems like it should scale when on smaller screens. But I am not sure about the second example, how do you interpret it on the [existing guide](https://engineering.18f.gov/architecture-reviews/data-act-pilot/#validation-rules)? It gets cut off and seems like it might be more of example of what data might look like, rather than a real table.

**Comment by echappen** [comment]
Since this is the same as previous behavior, I'm fine with continuing with this PR and making a separate issue to explore further.

**Review by echappen — APPROVED** [review]
Approved from an engineering standpoint 👍

**Pull request merged**
