### PR TITLE
Activate codeowners for a11y, eng-hiring, engineering, product guides

### PR DESCRIPTION
**Pull request by echappen**
## Changes proposed in this pull request:

- Activate github codeowners for these guides, so that they'll be notified of pull requests for their guide

## security considerations

None as this is not a functional change

### CODE REVIEW

**Comment by echappen** [comment]
@amymok @allisonnorman @jasnakai Can you please confirm that you'll be the owner of these guides? (Listed [here](https://github.com/18F/guides/pull/267/files#diff-3d36a1bf06148bc6ba1ce2ed3d19de32ea708d955fed212c0d27c536f0bd4da7R25).) This change will make it so that you'll be notified when a guide that you own has proposed changes.

**Comment by amymok** [comment]
@echappen yes.

**Comment by echappen** [comment]
@jduss4 This is ready for review/merge

**Review by jduss4 — APPROVED** [review]

**Comment by jasnakai** [comment]
Sorry I missed this. Yes for me. Thank you @echappen !

**Pull request merged**
