### PR TITLE
'Stakeholder influence mapping' Methods card print layout fix

### PR DESCRIPTION
**Pull request by sam-couch-18f**
Changes related to https://github.com/18F/TLC-crew/issues/628

## Changes proposed in this pull request:
- Small tweaks to **What** and **Why** sections for readability and em-dash usage
- Updates to **How to do it** section that make steps more concise and allow the content to fit within the print view container

| Before (Web View) | After (Web View) |
| :--------: | :-------: |
|  |  |
| **Before (Print View)** | **After (Print View)** |
|  |  |

## security considerations
N/A

### CODE REVIEW

**Comment by melchoyce** [comment]
Would it be out of scope to adjust the line-height on the h1 here? It should probably be `line-height: 1.3;`.

**Comment by melchoyce** [comment]
I'll make an issue!

Visually your afters all look good, but I'll let a content designer chime in for final approval.

**Comment by bpdesigns** [comment]
@amandacostello @durland18F @quarterback content eyes requested on this

**Comment by durland18F** [comment]
Hey folks! 18F style is to have spaces around em dashes. Otherwise looks good.

**Comment by bpdesigns** [comment]
Thanks @durland18F Here is more on our [style](https://guides.18f.gov/content-guide/our-style/) @sam-couch-18f

**Comment by bpdesigns** [comment]
@sam-couch-18f With @durland18F s edit this is good to go! TY

**Review by bpdesigns — APPROVED** [review]

**Comment by bpdesigns** [comment]
Thanks @sam-couch-18f please feel free to close

**Pull request merged**
