### PR TITLE
De-risking Guide v2: Add some resource pages

### PR DESCRIPTION
**Pull request by nateborr**
## Changes proposed in this pull request:

Note that these changes will be added to the `derisking-government-tech` feature branch, and not yet merged into main or deployed.

### Add tags to the `<main>` element in the wide layout

Update the wide layout to add any tags as classes to the `<main>` HTML element, following the pattern we use in the page layout. This allows the resource index and evaluating-bids pages to use the wide layout with CSS styles that are namespaced to the derisking-government-tech pages.

I only see the wide layout being used elsewhere by the Color palette page within the Brand guide, so potential impact of that change is minimal and easy to manually test.

### New content

Implement the first three resource appendix sections for the v2 de-risking guide.

- The Resources index page
- Market research
- Verbal interview questions
- Evaluating bids, including the web and PDF versions of the evaluator worksheet

## Layout and style notes

To potentially reduce scope prior to launch, I've left out some custom design elements that may not have a high return compared to the engineering effort. @melchoyce I'll look to your review of what's required and what can be done post-launch or descoped.

### Page layouts

As with the About page, I've used existing Guides page layouts that align content to the left side of the screen, rather than centering it as called for in some of the resource page designs.

### Resources page cards

I've kept the default gaps between cards from the USWDS usa-cards components, rather than matching the somewhat wider spacing from the design.

### Numbered list markers on the market research page

Rather than customizing the list numbers at the top of the page ("1" and "2" with circles around them) I have standard ordered-list markers there. (I used an ordered list rather than a flex layout to preserve the page hierarchy for accessibility reasons.)

### Anchor links on the evaluator worksheet subheadings

I used standard HTML headings within the evaluator worksheet; the Guides site automatically wires up anchor tags and link icons next to them, which show up if you print the web version of the worksheet.

## Testing

Beyond the automated validations on the PR, manually test the following on a PR build:

### Newly implemented sections

For each of the `Resources`, `Market research`, `Verbal interview questions`, `Evaluating bids`, and `Evaluator worksheet` pages:

- Visit the /derisking-government-tech/ route on the PR build URL and confirm you can reach the pages in question via the Resources link in the top nav. Note that the evaluator worksheet is only linked internally from the Evaluating bids page: https://federalist-8bc0b42c-5fd0-4ae8-9366-cd9c265a4446.sites.pages.cloud.gov/preview/18f/guides/drg-v2-add-initial-resources/derisking-government-tech/
- Confirm that the content, layout, and images on the page look correct
- Confirm that links on the page go to the expected destinations
- On the evaluating-bids and evaluator-worksheet pages, confirm that the download links open the PDF version of the worksheet
- Check mobile device rendering using browser dev tools
- Shake out the page's responsiveness when the browser window is resized
- Confirm meta title, meta description, and social meta tags are present in the page source
- Shake out the top nav and, where present, the left nav

### Pages potentially affected by refactoring

There should not be any changes in the following, but since I modified some styles or layouts they use, shake them out and confirm they still look correct.

- [`/brand/color-palette/`](https://federalist-8bc0b42c-5fd0-4ae8-9366-cd9c265a4446.sites.pages.cloud.gov/preview/18f/guides/drg-v2-add-initial-resources/brand/color-palette/)
- [`/derisking-government-tech/#what-s-in-this-guide`](https://federalist-8bc0b42c-5fd0-4ae8-9366-cd9c265a4446.sites.pages.cloud.gov/preview/18f/guides/drg-v2-add-initial-resources/derisking-government-tech/#what-s-in-this-guide/)

## security considerations

No security considerations: These updates use the existing framework and patterns of the 18F Guides site.

### CODE REVIEW

**Comment by melchoyce** [comment]
The resource cards don't seem to be tiling on smaller screens:

image

> Numbered list markers on the market research page
> Rather than customizing the list numbers at the top of the page ("1" and "2" with circles around them) I have standard ordered-list markers there. (I used an ordered list rather than a flex layout to preserve the page hierarchy for accessibility reasons.)

This should be using the USWDS "Process List" component: https://designsystem.digital.gov/components/process-list/

If possible I'd really like us to get that in.

**Comment by nateborr** [comment]
@melchoyce I've added tiling behavior to the resource cards so that they show a single card per row for phone-sized mobile devices and two cards per row for smaller tablets. Let me know how that's looking; I can adjust those size thresholds as needed based on the [USWDS grid breakpoints](https://designsystem.digital.gov/utilities/layout-grid/#variables-2).

I'll rework the top of the market research page using a Process List.

**Comment by melchoyce** [comment]
Hey! Looks like the cards in the one-column layout still aren't taking up the full width of the page on desktop:

image

(It's acting correctly on mobile)

**Comment by nateborr** [comment]
@melchoyce The resources and market research pages are ready for re-review.

**Review by melchoyce — APPROVED** [review]
LGTM!

**Review by peterrowland — APPROVED** [review]
√

**Pull request merged**
