### PR TITLE
Add github workflow to automerge dependabot patches

### PR DESCRIPTION
**Pull request by echappen**
Closes issue #109

## Changes proposed in this pull request:
- Adds github workflow yml file to automerge any pull requests from dependabot for patch updates, using [this example](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#enable-auto-merge-on-a-pull-request). I removed the check for certain dependency names because we want this to happen for all dependencies. 

## security considerations

- if implemented incorrectly, could auto-merge other types of PR's. Can mitigate this risk by monitoring PR merges for the next few days after merging this.

### CODE REVIEW

**Comment by igorkorenfeld** [comment]
We do have branch protection set up, but at the same time I know that early on there were some PRs merged that had failing checks. Wondering if there is something that we need to update? 

screenshot of the branch protection settings for this repo

**Comment by eric-gade** [comment]
@igorkorenfeld I think we definitely want that second box checked, as it would prevent timing issues when merging long standing PRs and making CI changes (I think?)

**Comment by echappen** [comment]
@eric-gade Agreed, good catch! @igorkorenfeld I don't have access to those settings—would you be able to check the box to require branches to be up-to-date before merging?

**Comment by igorkorenfeld** [comment]
Of course! The note says 
> This setting will not take effect unless at least one status check is enabled (see below).

Should I search and select all of them - `build`, `pa11y-scan`, `Run linter`, `validate html`, and `Check all links` ?

**Comment by echappen** [comment]
Hmm I'm not sure, but I think we'd want all of them?

**Comment by echappen** [comment]
The reason I say that is because I think that will keep our checks consistent, but I'm still not sure how or why status checks come into play for that particular setting. I'm willing to just decide and see how it goes.

**Comment by igorkorenfeld** [comment]
That make sense, I added all five.

**Comment by echappen** [comment]
TY!

**Pull request merged**
