### PR TITLE
Add link icons for locked and external links

### PR DESCRIPTION
**Pull request by igorkorenfeld**
## Changes proposed in this pull request:
This PR adds a "lock" icon for links that are private (e.g. require a login or account) and the USWDS "launch" icon for external links. Based on https://github.com/18F/ux-guide/issues/297 external links are defined as "Any link that is not a federal .gov or .mil website". There seems to be no way to programmatically distinguish between a federal and a non-federal .gov domain. As such, the check for external domains only looks for a ".gov" TLD, and therefore will not label non-federal .gov domains as external automatically. There are only a handful of non-federal .gov links used throughout our guides, and those will need to be tagged manually. 

The implementation is based on the [approach](https://github.com/18F/handbook/blob/main/config/plugins/privateLinks.js) used in the 18F handbook, but uses the renderer in `markdown-it` instead of 11ty's `transform`.

This resolves the programmatic icon adding in  TLC/#341

👓 [Preview](https://federalist-8bc0b42c-5fd0-4ae8-9366-cd9c265a4446.sites.pages.cloud.gov/preview/18f/guides/ik/link-icons/)

### CODE REVIEW

**Review by juliaklindpaintner — APPROVED** [review]
I poked through a few of the guides and it all looked good to me! I'm seeing the locks and the launch icons show up in what seem to be the appropriate places.

**Comment by michelle-rago** [comment]
There are external link icons for digital.gov links (and other federal gov links) on https://federalist-8bc0b42c-5fd0-4ae8-9366-cd9c265a4446.sites.pages.cloud.gov/preview/18f/guides/ik/link-processing/accessibility/.  Examples: Section 508, Accessibility for Teams, USWDS.

This page has external link icons on a digital.gov link and on the TTS handbook https://federalist-8bc0b42c-5fd0-4ae8-9366-cd9c265a4446.sites.pages.cloud.gov/preview/18f/guides/ik/link-processing/product/resources/.

Should I be reviewing these pages?

Side note: The HTML page title on https://federalist-8bc0b42c-5fd0-4ae8-9366-cd9c265a4446.sites.pages.cloud.gov/preview/18f/guides/ik/link-processing/ is "Home | 18F 18F Approaches."

**Comment by igorkorenfeld** [comment]
Thank you for catching those Michelle! You don't have to review the pages, but very much appreciate the ones that you did.

**Comment by juliaklindpaintner** [comment]
Sorry for my less than thorough review and thank you for clarifying that our review wasn't necessary and already taking steps to address the auto-tagging of reviewers. I did happen to just notice at the top of t[his page](https://federalist-8bc0b42c-5fd0-4ae8-9366-cd9c265a4446.sites.pages.cloud.gov/preview/18f/guides/ik/link-processing/product/resources/) that it looks like there are empty parentheses at the end of the first paragraph of text that is supposed to preview the lock icon, I believe. That may be an issue across other guides resources pages as well if that same paragraph is included, too.

**Comment by igorkorenfeld** [comment]
No worries at all, and thank you for pointing that out! I will take a look. 

For any other reviewers I noticed that my original preview link was going to the wrong branch. I've updated it in the PR description, but just for extra clarity the correct one is:

https://federalist-8bc0b42c-5fd0-4ae8-9366-cd9c265a4446.sites.pages.cloud.gov/preview/18f/guides/ik/link-icons/

**Review by jasnakai — APPROVED** [review]
These look good to me. I did notice the empty parentheses  that Julia pointed out. I'm not sure that is how to properly display the icon without the anchor link markup. So not sure if this is an issue for this PR.
Also noticed that the permalink icons are not properly structured for accessibility but that is not part of this PR.

**Comment by igorkorenfeld** [comment]
Created a new TLC issue ([522](https://github.com/18F/TLC-crew/issues/522)) for the permalink structure issue.

**Pull request merged**
