### PR TITLE
Deploy Agile guide

### LINKED ISSUE #80: Bug: fix styling for 404 page
The 404 page could use some design love, like a grid-container around the main content.

This may also entail finding a solution for fixing the footer to the bottom of the viewport when page content is really short.

Screenshot of current state:
 
Screen Shot 2023-10-13 at 3 04 31 PM

### PR DESCRIPTION
**Pull request by eric-gade**
## Changes proposed in this pull request:
This PR is a partial fulfillment of https://github.com/18F/TLC-crew/issues/447, and will make the Agile guide live on the new site.
  
Changes include
- Resolving all TODOs, especially in the links
- Manually updating external links to have the correct styling (per #88)
- Fixing the 404 page (closes #80)
- Ensuring that our custom guides 404 page will display as the 404 page in Cloud Pages
- Removing agile from the redirects list, so that the new guide is shown and the user is no longer redirected

## security considerations
No known security concerns
  
## Closes
#80

### CODE REVIEW

**Review by peterrowland — APPROVED** [review]
√

**Comment by peterrowland** [comment]
One note we might want to consider separately - Right now I think users will only see the message about moving to a new URL on the guides that have been migrated, which might be confusing.

**Comment by MelissaBraxton** [comment]
Great catch, @peterrowland! Flagging Peter's comment re: the banner not being consistent accross pre- and post-replatforming guides for @christophermather to think about how y'all might want to prioritize this. @igorkorenfeld can likely help give a sense of the level of effort.

**Comment by alexbielen** [comment]
We've been pretty strict about not updating the existing guides, so I think that if there's a solution where we can avoid that I'd be in favor of that!

**Comment by eric-gade** [comment]
> One note we might want to consider separately - Right now I think users will only see the message about moving to a new URL on the guides that have been migrated, which might be confusing.
  
I say we open a separate issue to explore that.

**Pull request merged**
